version: '3'

services:
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: raft
      MYSQL_USER: raft
      MYSQL_PASSWORD: raft
      MYSQL_ROOT_PASSWORD: secret
    ports:
     - 3306:3306
