#!/bin/bash
cmd=$1

function start_node1() {
	echo "---- start node1 ----"
	go run *.go -config ./conf/app1/app1.ini
}
function start_node2() {
	echo "---- start node2 ----"
	go run *.go -config ./conf/app2/app2.ini
}
function start_node3() {
	echo "---- start node3 ----"
	go run *.go -config ./conf/app3/app3.ini
}


function add_node_2() {
	echo "---- add node 2 ----"
	curl -L http://127.0.0.1:12380/2 -XPOST -d http://127.0.0.1:22379
}
function add_node_3() {
	echo "---- add node 3 ----"
	curl -L http://127.0.0.1:12380/3 -XPOST -d http://127.0.0.1:32379
}


function del_node_2() {
	echo "---- del node 2 ----"
	curl -L http://127.0.0.1:12380/2 -XDELETE
}
function del_node_3() {
	echo "---- del node 3 ----"
	curl -L http://127.0.0.1:12380/3 -XDELETE
}


function add_key_value() {
	local key=$1
	local value=$2
	curl -XPUT http://127.0.0.1:12380/$key -d "$value"
	echo "---- add key: $key, value: $value ----"
}

function get_key() {
	local key=$1
	value=`curl -XGET http://127.0.0.1:12380/$key` 
	echo "---- s1 => get key: $key, value: $value ----"
	value=`curl -XGET http://127.0.0.1:22380/$key` 
	echo "---- s2 => get key: $key, value: $value ----"
	value=`curl -XGET http://127.0.0.1:32380/$key` 
	echo "---- s3 => get key: $key, value: $value ----"
}

function del_key() {
	local key=$1
	value=`curl -XDELETE http://127.0.0.1:12380/$key`
	echo "---- del key: $key ----"
}

case $cmd in
	"s1")
	start_node1
;;
	"s2")
	start_node2
;;
	"s3")
	start_node3
;;
	"a2")
	add_node_2
;;
	"a3")
	add_node_3
;;
	"d2")
	del_node_2
;;
	"d3")
	del_node_3
;;
	"add")
	add_key_value $2 $3
;;
	"get")
	get_key $2
;;
	"cls")
	rm -rf raft-app-*
;;
	*)
	echo "no such command support"
esac
